### ISSUE TITLE
Flet program keeps on running.

### ISSUE THREAD

**Issue by dynstat** [ndonkoHenri/Flet-as-System-Tray-Icon#3]
The flet program doesn't stop when the app is closed using the "close button" in the title bar.

**Comment by ndonkoHenri** [comment]
Hey there.
Please what do you mean? 
What happens instead?
Any image?

**Comment by dynstat** [comment]
After clicking on the app window's "close button", the app window disappears but it does Not get closed in the terminal.. the process keeps on running.
Though the app gets closed normally (in the terminal as well) by using the "Close app" menu from the system tray menu options of the app.

**Comment by ndonkoHenri** [comment]
Thanks for your feedback.
I will push a commit to fix it.

**Comment by ndonkoHenri** [comment]
Please try it again, and let me know.
I just pushed a [commit](https://github.com/ndonkoHenri/Flet-as-System-Tray-Icon/commit/3b4ed623826669adada45bf7a6144b975dc6a70d) for it.
